### ISSUE TITLE
古地図のデフォルトの表示サイズはどう変更するのでしょうか

### ISSUE THREAD

**Issue by snowdrops89** [code4history/Maplat#174]
はじめまして。
Qiitaの記事を拝読し、触ってみました。
MaplatEditorで簡単な地図を作成し、それをMaplat Coreに取り込む事は出来ました。
が、どうしても、start_fromを古地図側にすると、古地図が一番小さく縮小された状態で表示されてしまいます。
osmなど、現代の地図にすれば、default_zoomで設定した倍率で表示されるのですが・・・
CodeSandBoxでのサンプルではそうなっていないので、おそらくわたしの方でナニか足りてないのだと思うのですが、記載されている設定項目は他に該当するようなのも見当たらず、exampleなど眺めて見るもぜんぜん分からず・・・
（CDNから設定→今はdistributionをダウンロードさせていただいてlocalhostでしていますが、現象的には変わらないです）
ご教授願えれば幸いです。

**Comment by kochizufan** [comment]
十分なドキュメントがなくて申し訳ありません。

まず、実は設定で古地図側の表示ズームを調整する機能はありません。
次の開発で追加するようにしたいと思います（それまでこのIssueは開いておきます）。

ですが、API経由で制御できます。

```
Maplat.createObject(option).then(function(app){
    const viewpoint = {
        zoom: 3
    }
    app.core.setViewpoint(viewpoint);
});
```

のような形で、地図の表示サイズその他の視点の設定が指定できます。

viewpointオブジェクトには以下の6通りの値が指定できます。

* **x, y:** 古地図の座標上でのx, y座標に移動します。左上が0,0原点の、元画像サイズでのピクセル座標です。
* **longitude, latitude:** 地球上での経緯度(WGS84)です。
* **zoom:** 古地図の座標上でのズームです。ズーム0は、古地図全体が256x256ピクセル以内に収まる大きさです。ズーム1はズーム0の縦横2倍（面積4倍）の大きさ、ズーム2はズーム0の縦横4倍（面積16倍）の大きさ...と倍々の大きさになっていって、元画像サイズになるズームサイズまで存在します。
* **mercZoom:** メルカトル座標上でのズームです。世界全体が256x256ピクセルに収まるのをズーム0、ズームが2上がるごとに倍々になる、Googleマップのズームと同じです。
* **rotation:** 古地図の正位置を角度0としての、回転量を指定します。
* **direction:** 北が上になるのを角度0としての、回転量(方角)を指定します。

**Comment by snowdrops89** [comment]
ご返信ありがとうございます！
おかげさまで、出来ました！！
（ボタンのイベントではなくマップを開いた時に反映させるためには、setTimeoutを噛ませないと、うまく作動しないようでした）
exampleに見える以外にも、APIがあるのですね。
リファレンスを充実させたいところですね☆
UI版で出来るような半透明の重ね合わせは、APIからも制御出来るのでしょうか？

**Comment by kochizufan** [comment]
app.core.setTransparency(ratio)

で、前景地図の透明度を設定できます。
すみません、恥ずかしながら0-1の値だったか0-100の値だったかは忘れてしまいました...。
試してみていただけたら...

> setTimeoutを噛ませないと、うまく作動しないようでした

これもうまくする方法があったはずなんですけど、ちょっと調べてみます。

> リファレンスを充実させたいところですね☆

自分が一番のユーザとしてやりたいことが山ほどあるのと、あまり使ってくれる人がいないので、どうしても新しい機能をつける方に邁進して、リファレンスに時間を割いてもどうせ誰も使ってくれないしなあ...とか考えがちになってしまってすみません。
せめて質問受けたことだけでもFAQなどにまとめてみようかと思います。
こんなことできる？など随時聞いていただければ、やり方をお伝えするか、機能がなければ作ります。

**Comment by snowdrops89** [comment]
ありがとうございます！
できました！！
お試ししたところ、ratioは0-100の値で、ベースの地図側の透明度という仕様のようでした。
わたしも、出来たことはなるべくQiitaとかに書き残しておくようにいたしますね☆

setTimeoutは、大丈夫ですよ～。
１とかで普通に動き、動作上は全く問題ありません。

それと・・・
わたしは、「[日本語プログラミング言語なでしこ](https://nadesi.com/)」というのを使用していて、ｖ３はJavascriptベースなのですが、これでMaplatが使えるようにプラグインを作りたいと思いますが良いですか？
こんな風に書けるようになるイメージです☆
```
「test」のMaplat作成した時には、
　　３で古地図ズーム。
　　０で地図回転。　// 北を上
　　OSMボタンをクリックした時には、
　　　「osm」に表示地図変更。
　　ここまで。
ここまで。
```
ワタクシこれじゃないとプログラムが作れぬのです（汗）
まあ、ほとんどわたしくらいしか使わないかもなのですが、一応うまく出来たらユーザープラグインとして公開させて頂きたいと思っています。

**Comment by kochizufan** [comment]
本当ですか！

Maplatが他の環境でも動くような形になると嬉しいです。
もしこまめなサポートがいるようであれば、Code for Historyの協力者向けに情報交換用のSlackなども作っているので、そちらにご招待することもできるので、必要であればお声がけください。
とても楽しみです。

**Comment by snowdrops89** [comment]
こんばんは。
　Slackが何か、検索しちゃったわたしでした（＾▽＾；
　ここに書くより、そっちの方がご都合がよろしいでしょうか？
　とりあえず、いくつかご質問です～。

①setViewpointのx,yがよく分かりません。
　「古地図の座標上でのx, y座標に移動します」ということなので、
```
  const viewpoint = {
    x: 0,
    y: 0
  }
    app.core.setViewpoint(viewpoint);
```
　とすれば、古地図が正位置の場合の、左角に移動するような気がしたのですが、どうもうまくいかないというか、x,yに何を入れても、同じ右下の中途半端な位置（？）に飛んでしまう感じで、ナニか根本的に間違いがあるでしょうか？

②createObjectのoptionに指定出来る物を教えて下さい。
　「enableHideMarker」「enableBorder」「enableShare」で、UIボタンが追加できることや、たぶんMapboxを使うための設定があるっぽいことは発見したのですが、他にも何かありますでしょうか？

③addLineで描画したものを消すことはできませんか？
　また、パスが閉じていた場合に中を塗ることは出来ませんか？
（何がしたいかというと、大火の焼失地域を表示してみたり、町人地と武家地を塗り分けてみたり？）

④assetsの中身のイメージやfontなどの位置は、固定でしょうか？　場所を指定して、ヨソから引っ張れるような設定はないでしょうか？

⑤ベース地図を複数登録した場合、osmが一番上になっていれば問題ないのですが、gsiやオルソを上にした時でも、最初に表示される地図は常にosmなんですが、地図選択のUIでは、一番上に指定したやつのサムネが表示されちゃうみたいなんですが、これはバグでしょうか？

　こんな感じです。①と⑤が確認できます。

> https://snowdrops89.github.io/Maplat_test/test/test_1.html

　まとめてで、しかも取り留めない感じでスミマセン。
　バグっぽいものは新規issueにした方が良かったかもなのですが、自分が間違ってるのかもしれず、全体的によく分からないので、これは直すやつ！　となったら改めてissueにする方向で;;;

**Comment by kochizufan** [comment]
> ここに書くより、そっちの方がご都合がよろしいでしょうか？

Githubの上って、汎用的な議論ができる場がないんですよね。
今話しているこの場も、本来は「古地図のデフォルトの表示サイズはどう変更するのでしょうか」についてのみ話し合う場ですし（別に問題はないのですが）。
なので、Slackだと何でも話せますし、打ち合わせの経緯も蓄積できますが、問題はSlackだと公開議論にならないので、もし公開の場で議論がしたければ他の場所を用意する必要がありますね。

> ①setViewpointのx,yがよく分かりません。

忘れてました！
この際の座標系って、ピクセル座標系ではなく、もっと特殊な座標系で、直観的には使いにくいものなのでした。
ピクセル座標系で指定するには、追加開発が必要ですね。
もしこの機能が必要であれば、issueを切っていただければ助かります。

> ②createObjectのoptionに指定出来る物を教えて下さい。

書かれたものの他には、
* overlay: trueだと、古地図表示の際に、背景に正確な地図を表示します。falseだと白背景になります。デフォルトはtrueで、オフにしたい時だけfalseを指定します。この設定は、MaplatCoreでも共通です。
* stateUrl: 表示地図の切り替え、表示場所の移動など表示状況が更新されると、自動的にURLが更新され、そのURLを使って、表示状況を他人にシェアできるようになります。デフォルトはfalseで、その場合、URLは自動更新されません。この設定は、MaplatCoreにはありません。
* enableCache: 地図の画像を、オフラインで利用できるように、ブラウザ側にキャッシュできるようになります。キャッシュは、表示した地図の範囲は勝手にキャッシュされる他、UIの一括ダウンロードを使って一括ダウンロード、キャッシュ削除を使ってキャッシュ解放を行えます。デフォルトはfalseで、この設定は、MaplatCoreにはありません。また、最近の仕様変更で、この機能はPWAという機能を有効にしなければ、設定していても動作しないようになっています。
* lang: アプリの言語設定を変更します。通常はブラウザ設定から自動取得しますが、明示的に指定したい時に利用します。対応しているのは、日本語、英語、中国語（繁体、簡体）、韓国語です。
* icon: POIのピンを変更したい時に、ピン画像のURLを指定します。これは地図、及び個々のPOIの中でも指定できるので、より個別POIに近い設定が優先して採用されます（例：アプリと個別POI両方でiconが指定されていれば、個別POIの設定が利用される）
* selectedIcon: POIの選択中のピンを変更したい時に、ピン画像のURLを指定します。これは地図、及び個々のPOIの中でも指定できるので、より個別POIに近い設定が優先して採用されます
* restore: アプリ起動時に表示する範囲を指定します。アプリ起動直後にsetViewpointを行うのとほぼ同じ動作になるかと思います。
* disableNoimage: デフォルトはfalseですが、trueにすると、POIにイメージが設定されていないと大きく「No Image」の代替画像が表示されるのをオフにします。
* control: UIコントロールの画像を変更します。まとめて設定を行うオブジェクトを指定しますが、例えばこんな感じです。
```
        control: {
            zoom_minus: "parts/minus.png",
            zoom_plus: "parts/plus.png",
            attr: "parts/attr.png",
            gps: "parts/gps.png",
            home: "parts/home.png",
            help: "parts/help.png",
            compass: "parts/compass.png",
            share: "parts/share.png",
            slider_in_help: "parts/slider.png",
            slider_color: "#92c7dc",
            favicon: "parts/favicon.png"
        },
```
* mapboxgl: Mapboxと連携したい際に、外で読み込んだMapbox GL JSのオブジェクトをこれに与えます。
* mapboxToken: MapboxのAPIトークンを指定します。
主なところはこんな感じでしょうか。PWAという技術をご存じであれば、それに関する設定もあるので、ご要望があれば説明しますが、PWAが何かについては煩雑になるので割愛させてください。

> addLineで描画したものを消すことはできませんか？
これは、clearLine()という命令で、全部の線を一斉に消すことはできます。個別に消すことは今のところできません。
個別に消す機能が必要であればissueでお願いします。

> また、パスが閉じていた場合に中を塗ることは出来ませんか？
これは閉じたパスというよりはポリゴンを追加したいという要望かと思いますが、ポリゴン追加は今のところできません。
必要であればissueでお願いします。
また、Lineの線の定義は完全に下の定義を流用していますので、下のURL内でOptionとして指定できるものは全部使えるはずです。
https://openlayers.org/en/latest/apidoc/module-ol_style_Stroke-Stroke.html

> assetsの中身のイメージやfontなどの位置は、固定でしょうか？　場所を指定して、ヨソから引っ張れるような設定はないでしょうか？

主に変更したくなるのはPOIピンの画像やUIの画像だと思いますが、それらは上のicon、selectedIconやcontrolの設定で変更できます。
他に変更したい要素があれば、issueでご指摘ください。

> ⑤ベース地図を複数登録した場合、osmが一番上になっていれば問題ないのですが、...これはバグでしょうか？

これはバグっぽいですね...issueで挙げていただけると助かります。

**Comment by snowdrops89** [comment]
ありがとうございます！！！
取り急ぎ、③と⑤について、新規issueを立てました（clearLineはできました！）
①については私に必要かどうかと言うとそれ程でも無くて、保留にしておきます（ただプラグインに実装しようとしてみたら、うまくいかなくて悩んでいたのでした）

②いっぱいありがとうございます！
PWA分かります☆　・・・ので、よろしくお願いします。

> Githubの上って、汎用的な議論ができる場がないんですよね
そうなんですよね。issueにする前の段階というか・・・（気にせず全部新規issueにして解決したらクローズすれば良かったのかもでしたが）
というわけで、Slackをインストールしてみました・・・が・・・どうしたらよいでしょうか？

**Comment by kochizufan** [comment]
Maplat UI側の機能としては完了しました。
各地図の設定ファイル（MaplatEditorで造られるもの）のJSONに、
homePosition: [経度,緯度]
mercZoom: Google Mapsなどと同じ定義でのズーム(少数指定可能)
をつけると、そこをホーム移動時の中心にできます。
もし指定しなければ、これまでと同様に地図の中心＆適当に計算されたサイズとなります。

ただ現状、MaplatEditorでこの設定ができないので、MaplatEditor側で設定できるようになって対応完了かなと思います。

あと、このチケット見て、PWA関連の設定お伝えしてなかったの思い出したので、そっちはSlackでフォローします。
