### ISSUE TITLE
ベース地図を複数登録した場合に表示地図とUIのサムネイルが一致しない

### ISSUE THREAD

**Issue by snowdrops89** [code4history/Maplat#177]
ベース地図を複数登録した場合、osmが一番上になっていれば問題ないのですが、gsiやオルソを上にした時でも、最初に表示される地図は常にosmになりますが、地図選択のUIのサムネイルでは一番上に指定した地図が表示されてしまう。

例えば設定がこうなっていた場合、
```
  "sources": [
    {
      "mapID": ～古地図の設定～
    },
    "gsi",
    "osm",
    "gsi_ortho"
  ],
```
表示される地図はOSMでサムネイルはGSIということになってしまいます。

> https://snowdrops89.github.io/Maplat_test/test/test_1.html

**Comment by kochizufan** [comment]
https://trello.com/c/nEeNWYs8/4-%E3%83%99%E3%83%BC%E3%82%B9%E5%9C%B0%E5%9B%B3%E3%82%92%E8%A4%87%E6%95%B0%E7%99%BB%E9%8C%B2%E3%81%97%E3%81%9F%E5%A0%B4%E5%90%88%E3%81%AB%E8%A1%A8%E7%A4%BA%E5%9C%B0%E5%9B%B3%E3%81%A8ui%E3%81%AE%E3%82%B5%E3%83%A0%E3%83%8D%E3%82%A4%E3%83%AB%E3%81%8C%E4%B8%80%E8%87%B4%E3%81%97%E3%81%AA%E3%81%84

**Comment by kochizufan** [comment]
@snowdrops89 
多分この件直ったはずです。
もし直っていなければ再オープンしてください。

ブランチはstart_mapで、以前の変更のvectorブランチの変更分も入っています。
